# Kitty window border colors
active_border_color     #C2842D
inactive_border_color   #C2842D
bell_border_color       #FFE49D

# Tab bar colors
active_tab_foreground   #1B1A18
active_tab_background   #DDCE4B
inactive_tab_foreground #1B1A18
inactive_tab_background #E3D7BF
tab_bar_background      #1B1A18

# Default colors (0-15)
color0  #1B1A18
color1  #C2842D
color2  #DDCE4B
color3  #FFE49D
color4  #92B482
color5  #E79856
color6  #C4D07E
color7  #E3D7BF
color8  #C3B7A5
color9  #FFB040
color10 #FFFCFF
color11 #FFFFFF
color12 #D4E2B9
color13 #FFD0AA
color14 #F9FFBC
color15 #E7E3D4

# Persistencia de colores base
foreground           #E3D7BF
background           #1B1A18
cursor               #E3D7BF
selection_foreground #1B1A18
selection_background #E3D7BF
