hl.on("hyprland.start", function ()
    hl.exec_cmd("steam -nochatui -nofriendsui -silent")
    hl.exec_cmd("solaar -w hide")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("sleep 1 && setxkbmap latam")
    hl.exec_cmd("linux-wallpaperengine --disable-mouse --scaling fill --silent --screen-root DP-2 --assets-dir /mnt/ssd/SteamLibrary/steamapps/common/wallpaper_engine/assets /mnt/ssd/SteamLibrary/steamapps/workshop/content/431960/3308717230")
end)
