"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
$character
"""

# palette = "matugen"
#
# [palettes.matugen]
# black = '#4b4732'
# red = '#C2842D'
# cyan = '#DDCE4B'
# yellow = '#FFE49D'
# blue = '#92B482'
# magenta = '#E79856'
# green = '#C4D07E'

[character]
success_symbol = "[󱞪](fg:green)"
error_symbol = "[󱞪](fg:red)"

[os]
disabled = false
format = "[](fg:black)[   ]($style)[](fg:black) "
style = "bg:black fg:green"

[directory]
format = "[](fg:black)[ 󰝰 $path ]($style)[](fg:black) "
style = "bg:black fg:blue"
truncation_length = 1
# truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:black"
symbol = " "

[git_branch]
format = "[](fg:black)[ $symbol $branch ]($style)[](fg:black) "
style = "bg:black fg:red"
symbol = ""

[git_status]
disabled = false
style = "bg:black fg:red"
format = '[](fg:black)([$all_status$ahead_behind]($style))[](fg:black) '
up_to_date = '[ ✓ ](bg:black fg:green)'
untracked = '[?\($count\)](bg:black fg:cyan)'
stashed = '[\$](bg:black fg:green)'
modified = '[!\($count\)](bg:black fg:cyan)'
renamed = '[»\($count\)](bg:black fg:green)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:black fg:cyan)'
ahead = '[⇡\(${count}\)](bg:black fg:magenta)'
diverged = '⇕[\[](bg:black fg:green)[⇡\(${ahead_count}\)](bg:black fg:magenta)[⇣\(${behind_count}\)](bg:black fg:yellow)[\]](bg:black fg:green)'
behind = '[⇣\(${count}\)](bg:black fg:yellow)'

[time]
disabled = true
format = " [](fg:black)[ $time 󰴈 ]($style)[](fg:black)"
style = "bg:black fg:yellow"
time_format = "%I:%M%P"
use_12hr = true

[cmd_duration]
format = "[](fg:black)[  $duration ]($style)[](fg:black) "
style = "bg:black fg:yellow"

# Languages

[c]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[elixir]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[elm]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[golang]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[haskell]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[java]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[julia]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[nodejs]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[scala]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = " "

[python]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$version ]($style)[](fg:black)"
disabled = false
symbol = ' '

[conda]
style = "bg:black fg:cyan"
format = " [](fg:black)[ $symbol$environment ]($style)[](fg:black)"
disabled = false
symbol = '🅒 '
